[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
otc = "3aF2PXcC92AyNJSkNMAA8rcDWo6fNttb6m4gs1E4seLA"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "bunx --bun ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

